/*
	Constants and enumerations to be used by the Tetris program. 
*/

#pragma once
#include "bgi\graphics.h"

const int BLOCKS_PER_GRID_WIDTH = 10;
const int BLOCKS_PER_GRID_HEIGHT = 1.5*BLOCKS_PER_GRID_WIDTH;
const int BLOCK_LENGTH = 40;
const int HEIGHT = BLOCKS_PER_GRID_HEIGHT*BLOCK_LENGTH+11;
const double INTERFACE_FRACTION = 0.4;
const int WIDTH = (BLOCKS_PER_GRID_WIDTH*BLOCK_LENGTH) / (1 - INTERFACE_FRACTION);
const int WINDOW_BORDER_X = 11;
const int WINDOW_BORDER_Y = 11;
const int DRAWABLE_WIDTH = WIDTH;
const int DRAWABLE_HEIGHT = HEIGHT;

const int INTERFACE_WIDTH = INTERFACE_FRACTION*DRAWABLE_WIDTH;
const int INTERFACE_HEIGHT = DRAWABLE_HEIGHT;
const int INTERFACE_COLOR = BLUE;
const int SECONDS_BEFORE_DROP = 1;
const int BASE_TIME_DELAY = 1000 * SECONDS_BEFORE_DROP;
const int BASE_LINE_CLEAR_SCORE = 100;

const int BACKGROUND_COLOR = DARKGRAY;
const int FONT_SIZE = 20;

const int DEFAULT_BLOCK_COLOR = INTERFACE_COLOR;
const int BLOCK_GRID_WIDTH = DRAWABLE_WIDTH-INTERFACE_WIDTH;
const int BLOCK_GRID_HEIGHT = DRAWABLE_HEIGHT;
//const int BLOCKS_PER_GRID_WIDTH = 10;
//const int BLOCK_LENGTH = BLOCK_GRID_WIDTH / BLOCKS_PER_GRID_WIDTH;// -2;
//const int BLOCKS_PER_GRID_HEIGHT = HEIGHT/ BLOCK_LENGTH ;
const int GRID_BLOCKS = BLOCKS_PER_GRID_HEIGHT * BLOCKS_PER_GRID_WIDTH ;

enum TetriminoType {
	I_TETRIMINO = 0, J_TETRIMINO, L_TETRIMINO, O_TETRIMINO, S_TETRIMINO, T_TETRIMINO, Z_TETRIMINO
};

enum TetriminoOrientation {
	TOP_FACING_TOP = 0, TOP_FACING_RIGHT, TOP_FACING_BOTTOM, TOP_FACING_LEFT
};

const int TETRIMINO_TYPE_COUNT = Z_TETRIMINO;
const int I_TETRIMINO_COLOR = CYAN;
const int J_TETRIMINO_COLOR = RED;
const int L_TETRIMINO_COLOR = BLUE;
const int O_TETRIMINO_COLOR = YELLOW;
const int S_TETRIMINO_COLOR = GREEN;
const int T_TETRIMINO_COLOR = LIGHTGRAY;
const int Z_TETRIMINO_COLOR = MAGENTA;

const int KEY_ENTER = 13;
const int KEY_SPACE = 32;
const int KEY_ESC = 27;

